name: C++ CI

on:
  push:
    branches: [main] # replace with main (if applicable)
    tags: '*'
  pull_request:
    branches: [main] # replace with main (if applicable)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++, clang++]
        cmake_config_flags: [-DBUILD_SHARED_LIBS=FALSE]
        include:
          - os: macos-10.15
            cxx: clang++
            cmake_config_flags: -DSFML_BUILD_FRAMEWORKS=FALSE -DSFML_DEPENDENCIES_INSTALL_PREFIX=$GITHUB_WORKSPACE/artifacts -DBUILD_SHARED_LIBS=FALSE
          - os: windows-2019
            cxx: cl
          - os: windows-2019
            cxx: g++
            cmake_generator: "\"MinGW Makefiles\""
            cmake_config_flags: -DBUILD_SHARED_LIBS=TRUE

    steps:
      - uses: actions/checkout@v2

      - name: Prepare env
        shell: bash
        run: |
          echo $GITHUB_WORKSPACE
          mkdir $GITHUB_WORKSPACE/build
          mkdir $GITHUB_WORKSPACE/artifacts
          cp CMakeListsGI.txt CMakeLists.txt
      # taken from SFML Github Actions
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev
      - name: Configure CMake
        env:
          CXX: ${{ matrix.cxx }}
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        # https://github.com/saxbophone/CPP20-Cross-Platform-Template
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: |
           CMAKE_GENERATOR=${{ matrix.cmake_generator }} cmake -S $GITHUB_WORKSPACE -B . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/artifacts ${{matrix.cmake_config_flags}}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE -j6

      - name: Install
        # working-directory: ${{ github.workspace }}/build
        shell: bash
        # Use CMake to "install" build artifacts (only interested in CMake registered targets) to our custom artifacts directory
        run: cmake --install build --config $BUILD_TYPE --prefix artifacts

      - name: Set Tag Name
        shell: bash
        # trim prefix from ref to get tag name
        run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> $GITHUB_ENV

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          type: 'zip'
          path: artifacts
          filename: release_${{ env.TAG_NAME }}_${{ matrix.os }}_${{ matrix.cxx }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release_${{ env.TAG_NAME }}_${{ matrix.os }}_${{ matrix.cxx }}.zip
